"""v4 minimal simulation framework."""

from .backtest import BacktestEngine, run_backtest
from .benchmarks import (
    compute_true_buy_and_hold,
    evaluate_standard_benchmarks,
    run_controller_buy_and_hold_benchmark,
    run_fixed_exposure_benchmark,
    run_zero_position_benchmark,
)
from .configs import (
    DAILY_CRYPTO_PERIODS_PER_YEAR,
    FOUR_HOUR_CRYPTO_PERIODS_PER_YEAR,
    HOURLY_CRYPTO_PERIODS_PER_YEAR,
    V41DefaultConfig,
    V41_VERSION_NAME,
    V42_CANDIDATE_A_DESCRIPTION,
    V42_CANDIDATE_A_VERSION_NAME,
    V42_CANDIDATE_B_DESCRIPTION,
    V42_CANDIDATE_B_VERSION_NAME,
    V42_CANDIDATE_C_DESCRIPTION,
    V42_CANDIDATE_C_VERSION_NAME,
    V42_CANDIDATE_D_DESCRIPTION,
    V42_CANDIDATE_D_VERSION_NAME,
    V42_CANDIDATE_E_DESCRIPTION,
    V42_CANDIDATE_E_VERSION_NAME,
    build_v41_controller,
    build_v41_estimator,
    build_v42_candidate_a_strategy,
    build_v42_candidate_b_strategy,
    build_v42_candidate_c_strategy,
    build_v42_candidate_d_strategy,
    build_v42_candidate_e_strategy,
    create_v41_default_config,
    make_v42_candidate_a_config,
    make_v42_candidate_b_config,
    make_v42_candidate_c_config,
    make_v42_candidate_d_config,
    make_v42_candidate_e_config,
    run_v41_backtest,
    run_v42_candidate_a_backtest,
    run_v42_candidate_b_backtest,
    run_v42_candidate_c_backtest,
    run_v42_candidate_d_backtest,
    run_v42_candidate_e_backtest,
)
from .controllers import BuyAndHoldController, ControllerConfig, FixedExposureController, MinimalContinuousController, ZeroController
from .data_types import BacktestConfig, FilteredSignals, Observation, StateVector
from .filters import FilterConfig, MinimalFilterLayer
from .interfaces import DummyStateEstimator, FilteredDummyStateEstimator, LongOnlyPositionConstraint
from .metrics import MetricsEvaluator, evaluate_metrics, evaluate_metrics_after_warmup
from .state_estimator import MinimalStateEstimator, StateEstimatorConfig

__all__ = [
    "BacktestConfig",
    "BacktestEngine",
    "BuyAndHoldController",
    "ControllerConfig",
    "DAILY_CRYPTO_PERIODS_PER_YEAR",
    "DummyStateEstimator",
    "FOUR_HOUR_CRYPTO_PERIODS_PER_YEAR",
    "FilteredDummyStateEstimator",
    "FilteredSignals",
    "FilterConfig",
    "FixedExposureController",
    "HOURLY_CRYPTO_PERIODS_PER_YEAR",
    "LongOnlyPositionConstraint",
    "MetricsEvaluator",
    "MinimalContinuousController",
    "MinimalFilterLayer",
    "MinimalStateEstimator",
    "Observation",
    "StateEstimatorConfig",
    "StateVector",
    "V41DefaultConfig",
    "V41_VERSION_NAME",
    "V42_CANDIDATE_A_DESCRIPTION",
    "V42_CANDIDATE_A_VERSION_NAME",
    "V42_CANDIDATE_B_DESCRIPTION",
    "V42_CANDIDATE_B_VERSION_NAME",
    "V42_CANDIDATE_C_DESCRIPTION",
    "V42_CANDIDATE_C_VERSION_NAME",
    "V42_CANDIDATE_D_DESCRIPTION",
    "V42_CANDIDATE_D_VERSION_NAME",
    "V42_CANDIDATE_E_DESCRIPTION",
    "V42_CANDIDATE_E_VERSION_NAME",
    "ZeroController",
    "build_v41_controller",
    "build_v41_estimator",
    "build_v42_candidate_a_strategy",
    "build_v42_candidate_b_strategy",
    "build_v42_candidate_c_strategy",
    "build_v42_candidate_d_strategy",
    "build_v42_candidate_e_strategy",
    "compute_true_buy_and_hold",
    "create_v41_default_config",
    "make_v42_candidate_a_config",
    "make_v42_candidate_b_config",
    "make_v42_candidate_c_config",
    "make_v42_candidate_d_config",
    "make_v42_candidate_e_config",
    "evaluate_metrics_after_warmup",
    "evaluate_metrics",
    "evaluate_standard_benchmarks",
    "run_controller_buy_and_hold_benchmark",
    "run_fixed_exposure_benchmark",
    "run_backtest",
    "run_v41_backtest",
    "run_v42_candidate_a_backtest",
    "run_v42_candidate_b_backtest",
    "run_v42_candidate_c_backtest",
    "run_v42_candidate_d_backtest",
    "run_v42_candidate_e_backtest",
    "run_zero_position_benchmark",
]
